export interface StockEntry {
  symbol: string;     // Yahoo Finance ticker
  name: string;       // Company name
  region: "US" | "Europe" | "Asia" | "Other" | "ETF & Leveraged";
}

export const STOCK_UNIVERSE: StockEntry[] = [
  // ─── ETF & Leveraged ──────────────────────────────────────
  { symbol: "SPY", name: "SPDR S&P 500 ETF Trust", region: "ETF & Leveraged" },
  { symbol: "QQQ", name: "Invesco QQQ Trust", region: "ETF & Leveraged" },
  { symbol: "IWM", name: "iShares Russell 2000 ETF", region: "ETF & Leveraged" },
  { symbol: "DIA", name: "SPDR Dow Jones Industrial Average ETF", region: "ETF & Leveraged" },
  { symbol: "UPRO", name: "ProShares UltraPro S&P500 (3x)", region: "ETF & Leveraged" },
  { symbol: "SPXU", name: "ProShares UltraPro Short S&P500 (-3x)", region: "ETF & Leveraged" },
  { symbol: "TQQQ", name: "ProShares UltraPro QQQ (3x)", region: "ETF & Leveraged" },
  { symbol: "SQQQ", name: "ProShares UltraPro Short QQQ (-3x)", region: "ETF & Leveraged" },
  { symbol: "UGAZ", name: "VelocityShares 3x Long Natural Gas ETN", region: "ETF & Leveraged" },
  { symbol: "DGAZ", name: "VelocityShares 3x Inverse Natural Gas ETN", region: "ETF & Leveraged" },
  { symbol: "UWT", name: "VelocityShares 3x Long Crude Oil ETN", region: "ETF & Leveraged" },
  { symbol: "DWT", name: "VelocityShares 3x Inverse Crude Oil ETN", region: "ETF & Leveraged" },
  { symbol: "SOXL", name: "Direxion Daily Semiconductor Bull 3X", region: "ETF & Leveraged" },
  { symbol: "SOXS", name: "Direxion Daily Semiconductor Bear 3X", region: "ETF & Leveraged" },
  { symbol: "FAS", name: "Direxion Daily Financial Bull 3X", region: "ETF & Leveraged" },
  { symbol: "FAZ", name: "Direxion Daily Financial Bear 3X", region: "ETF & Leveraged" },
  { symbol: "JNUG", name: "Direxion Daily Junior Gold Miners Index Bull 3X", region: "ETF & Leveraged" },

  // ─── US (~80) ─────────────────────────────────────────────
  { symbol: "AAPL", name: "Apple", region: "US" },
  { symbol: "MSFT", name: "Microsoft", region: "US" },
  { symbol: "GOOGL", name: "Alphabet (Google)", region: "US" },
  { symbol: "AMZN", name: "Amazon", region: "US" },
  { symbol: "NVDA", name: "NVIDIA", region: "US" },
  { symbol: "META", name: "Meta Platforms", region: "US" },
  { symbol: "TSLA", name: "Tesla", region: "US" },
  { symbol: "BRK-B", name: "Berkshire Hathaway", region: "US" },
  { symbol: "JPM", name: "JPMorgan Chase", region: "US" },
  { symbol: "V", name: "Visa", region: "US" },
  { symbol: "UNH", name: "UnitedHealth", region: "US" },
  { symbol: "JNJ", name: "Johnson & Johnson", region: "US" },
  { symbol: "XOM", name: "Exxon Mobil", region: "US" },
  { symbol: "WMT", name: "Walmart", region: "US" },
  { symbol: "MA", name: "Mastercard", region: "US" },
  { symbol: "PG", name: "Procter & Gamble", region: "US" },
  { symbol: "HD", name: "Home Depot", region: "US" },
  { symbol: "CVX", name: "Chevron", region: "US" },
  { symbol: "MRK", name: "Merck", region: "US" },
  { symbol: "ABBV", name: "AbbVie", region: "US" },
  { symbol: "LLY", name: "Eli Lilly", region: "US" },
  { symbol: "KO", name: "Coca-Cola", region: "US" },
  { symbol: "PEP", name: "PepsiCo", region: "US" },
  { symbol: "AVGO", name: "Broadcom", region: "US" },
  { symbol: "COST", name: "Costco", region: "US" },
  { symbol: "TMO", name: "Thermo Fisher", region: "US" },
  { symbol: "MCD", name: "McDonald's", region: "US" },
  { symbol: "CSCO", name: "Cisco", region: "US" },
  { symbol: "ACN", name: "Accenture", region: "US" },
  { symbol: "ABT", name: "Abbott Labs", region: "US" },
  { symbol: "DHR", name: "Danaher", region: "US" },
  { symbol: "NFLX", name: "Netflix", region: "US" },
  { symbol: "ADBE", name: "Adobe", region: "US" },
  { symbol: "CRM", name: "Salesforce", region: "US" },
  { symbol: "AMD", name: "AMD", region: "US" },
  { symbol: "INTC", name: "Intel", region: "US" },
  { symbol: "QCOM", name: "Qualcomm", region: "US" },
  { symbol: "TXN", name: "Texas Instruments", region: "US" },
  { symbol: "ORCL", name: "Oracle", region: "US" },
  { symbol: "PM", name: "Philip Morris", region: "US" },
  { symbol: "NKE", name: "Nike", region: "US" },
  { symbol: "UPS", name: "UPS", region: "US" },
  { symbol: "LOW", name: "Lowe's", region: "US" },
  { symbol: "MS", name: "Morgan Stanley", region: "US" },
  { symbol: "GS", name: "Goldman Sachs", region: "US" },
  { symbol: "BLK", name: "BlackRock", region: "US" },
  { symbol: "SCHW", name: "Charles Schwab", region: "US" },
  { symbol: "C", name: "Citigroup", region: "US" },
  { symbol: "BAC", name: "Bank of America", region: "US" },
  { symbol: "WFC", name: "Wells Fargo", region: "US" },
  { symbol: "AXP", name: "American Express", region: "US" },
  { symbol: "DE", name: "Deere & Co", region: "US" },
  { symbol: "CAT", name: "Caterpillar", region: "US" },
  { symbol: "BA", name: "Boeing", region: "US" },
  { symbol: "RTX", name: "RTX (Raytheon)", region: "US" },
  { symbol: "LMT", name: "Lockheed Martin", region: "US" },
  { symbol: "GE", name: "GE Aerospace", region: "US" },
  { symbol: "HON", name: "Honeywell", region: "US" },
  { symbol: "MMM", name: "3M", region: "US" },
  { symbol: "DIS", name: "Walt Disney", region: "US" },
  { symbol: "CMCSA", name: "Comcast", region: "US" },
  { symbol: "T", name: "AT&T", region: "US" },
  { symbol: "VZ", name: "Verizon", region: "US" },
  { symbol: "COP", name: "ConocoPhillips", region: "US" },
  { symbol: "SLB", name: "Schlumberger", region: "US" },
  { symbol: "GILD", name: "Gilead Sciences", region: "US" },
  { symbol: "BMY", name: "Bristol-Myers Squibb", region: "US" },
  { symbol: "PFE", name: "Pfizer", region: "US" },
  { symbol: "AMGN", name: "Amgen", region: "US" },
  { symbol: "MDT", name: "Medtronic", region: "US" },
  { symbol: "SYK", name: "Stryker", region: "US" },
  { symbol: "ISRG", name: "Intuitive Surgical", region: "US" },
  { symbol: "SPGI", name: "S&P Global", region: "US" },
  { symbol: "CB", name: "Chubb", region: "US" },
  { symbol: "NOW", name: "ServiceNow", region: "US" },
  { symbol: "UBER", name: "Uber", region: "US" },
  { symbol: "SQ", name: "Block (Square)", region: "US" },
  { symbol: "COIN", name: "Coinbase", region: "US" },
  { symbol: "PLTR", name: "Palantir", region: "US" },
  { symbol: "SNOW", name: "Snowflake", region: "US" },

  // ─── Europe (~40) ──────────────────────────────────────────
  { symbol: "ASML", name: "ASML", region: "Europe" },
  { symbol: "MC.PA", name: "LVMH", region: "Europe" },
  { symbol: "NESN.SW", name: "Nestlé", region: "Europe" },
  { symbol: "ROG.SW", name: "Roche", region: "Europe" },
  { symbol: "NOVN.SW", name: "Novartis", region: "Europe" },
  { symbol: "SAP", name: "SAP", region: "Europe" },
  { symbol: "OR.PA", name: "L'Oréal", region: "Europe" },
  { symbol: "SIE.DE", name: "Siemens", region: "Europe" },
  { symbol: "AZN", name: "AstraZeneca", region: "Europe" },
  { symbol: "SHEL", name: "Shell", region: "Europe" },
  { symbol: "TTE.PA", name: "TotalEnergies", region: "Europe" },
  { symbol: "HSBA.L", name: "HSBC", region: "Europe" },
  { symbol: "BP.L", name: "BP", region: "Europe" },
  { symbol: "ULVR.L", name: "Unilever", region: "Europe" },
  { symbol: "GSK.L", name: "GSK", region: "Europe" },
  { symbol: "RIO.L", name: "Rio Tinto", region: "Europe" },
  { symbol: "BARC.L", name: "Barclays", region: "Europe" },
  { symbol: "DGE.L", name: "Diageo", region: "Europe" },
  { symbol: "BN.PA", name: "Danone", region: "Europe" },
  { symbol: "AI.PA", name: "Air Liquide", region: "Europe" },
  { symbol: "SAN.PA", name: "Sanofi", region: "Europe" },
  { symbol: "BNP.PA", name: "BNP Paribas", region: "Europe" },
  { symbol: "ALV.DE", name: "Allianz", region: "Europe" },
  { symbol: "MBG.DE", name: "Mercedes-Benz", region: "Europe" },
  { symbol: "BMW.DE", name: "BMW", region: "Europe" },
  { symbol: "VOW3.DE", name: "Volkswagen", region: "Europe" },
  { symbol: "DTE.DE", name: "Deutsche Telekom", region: "Europe" },
  { symbol: "BAS.DE", name: "BASF", region: "Europe" },
  { symbol: "ENEL.MI", name: "Enel", region: "Europe" },
  { symbol: "ISP.MI", name: "Intesa Sanpaolo", region: "Europe" },
  { symbol: "NOVO-B.CO", name: "Novo Nordisk", region: "Europe" },
  { symbol: "ERIC-B.ST", name: "Ericsson", region: "Europe" },
  { symbol: "VOLV-B.ST", name: "Volvo", region: "Europe" },
  { symbol: "ABB", name: "ABB", region: "Europe" },
  { symbol: "UBS", name: "UBS", region: "Europe" },
  { symbol: "RACE", name: "Ferrari", region: "Europe" },
  { symbol: "SPOT", name: "Spotify", region: "Europe" },
  { symbol: "NVO", name: "Novo Nordisk (US ADR)", region: "Europe" },
  { symbol: "ING", name: "ING Group", region: "Europe" },
  { symbol: "PHG", name: "Philips", region: "Europe" },

  // ─── Asia (~40) ─────────────────────────────────────────────
  { symbol: "7203.T", name: "Toyota Motor", region: "Asia" },
  { symbol: "6758.T", name: "Sony", region: "Asia" },
  { symbol: "6861.T", name: "Keyence", region: "Asia" },
  { symbol: "9984.T", name: "SoftBank Group", region: "Asia" },
  { symbol: "6501.T", name: "Hitachi", region: "Asia" },
  { symbol: "7974.T", name: "Nintendo", region: "Asia" },
  { symbol: "8306.T", name: "Mitsubishi UFJ", region: "Asia" },
  { symbol: "9432.T", name: "NTT", region: "Asia" },
  { symbol: "4502.T", name: "Takeda", region: "Asia" },
  { symbol: "6902.T", name: "Denso", region: "Asia" },
  { symbol: "005930.KS", name: "Samsung Electronics", region: "Asia" },
  { symbol: "000660.KS", name: "SK Hynix", region: "Asia" },
  { symbol: "9988.HK", name: "Alibaba (HK)", region: "Asia" },
  { symbol: "0700.HK", name: "Tencent", region: "Asia" },
  { symbol: "3690.HK", name: "Meituan", region: "Asia" },
  { symbol: "1299.HK", name: "AIA Group", region: "Asia" },
  { symbol: "0941.HK", name: "China Mobile", region: "Asia" },
  { symbol: "2318.HK", name: "Ping An Insurance", region: "Asia" },
  { symbol: "RELIANCE.NS", name: "Reliance Industries", region: "Asia" },
  { symbol: "TCS.NS", name: "TCS", region: "Asia" },
  { symbol: "INFY.NS", name: "Infosys", region: "Asia" },
  { symbol: "HDFCBANK.NS", name: "HDFC Bank", region: "Asia" },
  { symbol: "ICICIBANK.NS", name: "ICICI Bank", region: "Asia" },
  { symbol: "HINDUNILVR.NS", name: "Hindustan Unilever", region: "Asia" },
  { symbol: "ITC.NS", name: "ITC", region: "Asia" },
  { symbol: "SBIN.NS", name: "State Bank of India", region: "Asia" },
  { symbol: "BHARTIARTL.NS", name: "Bharti Airtel", region: "Asia" },
  { symbol: "BAJFINANCE.NS", name: "Bajaj Finance", region: "Asia" },
  { symbol: "WIPRO.NS", name: "Wipro", region: "Asia" },
  { symbol: "LT.NS", name: "Larsen & Toubro", region: "Asia" },
  { symbol: "BABA", name: "Alibaba (US ADR)", region: "Asia" },
  { symbol: "JD", name: "JD.com", region: "Asia" },
  { symbol: "PDD", name: "PDD Holdings", region: "Asia" },
  { symbol: "BIDU", name: "Baidu", region: "Asia" },
  { symbol: "NIO", name: "NIO", region: "Asia" },
  { symbol: "TME", name: "Tencent Music", region: "Asia" },
  { symbol: "TSM", name: "TSMC (US ADR)", region: "Asia" },
  { symbol: "HDB", name: "HDFC Bank (US ADR)", region: "Asia" },
  { symbol: "SONY", name: "Sony (US ADR)", region: "Asia" },
  { symbol: "TM", name: "Toyota (US ADR)", region: "Asia" },

  // ─── Other (~40) ────────────────────────────────────────────
  { symbol: "BHP", name: "BHP Group", region: "Other" },
  { symbol: "CSL.AX", name: "CSL Limited", region: "Other" },
  { symbol: "CBA.AX", name: "Commonwealth Bank", region: "Other" },
  { symbol: "WBC.AX", name: "Westpac", region: "Other" },
  { symbol: "NAB.AX", name: "NAB", region: "Other" },
  { symbol: "ANZ.AX", name: "ANZ Bank", region: "Other" },
  { symbol: "WDS.AX", name: "Woodside Energy", region: "Other" },
  { symbol: "FMG.AX", name: "Fortescue", region: "Other" },
  { symbol: "WES.AX", name: "Wesfarmers", region: "Other" },
  { symbol: "WOW.AX", name: "Woolworths (AU)", region: "Other" },
  { symbol: "PBR", name: "Petrobras", region: "Other" },
  { symbol: "VALE", name: "Vale", region: "Other" },
  { symbol: "ITUB", name: "Itaú Unibanco", region: "Other" },
  { symbol: "NU", name: "Nu Holdings", region: "Other" },
  { symbol: "MELI", name: "MercadoLibre", region: "Other" },
  { symbol: "BSBR", name: "Banco Santander Brasil", region: "Other" },
  { symbol: "SQM", name: "SQM (Chile)", region: "Other" },
  { symbol: "GGAL", name: "Grupo Financiero Galicia", region: "Other" },
  { symbol: "YPF", name: "YPF (Argentina)", region: "Other" },
  { symbol: "GOLD", name: "Barrick Gold", region: "Other" },
  { symbol: "NEM", name: "Newmont", region: "Other" },
  { symbol: "AEM", name: "Agnico Eagle", region: "Other" },
  { symbol: "FNV", name: "Franco-Nevada", region: "Other" },
  { symbol: "WPM", name: "Wheaton Precious Metals", region: "Other" },
  { symbol: "SHOP", name: "Shopify", region: "Other" },
  { symbol: "TD", name: "Toronto-Dominion Bank", region: "Other" },
  { symbol: "RY", name: "Royal Bank of Canada", region: "Other" },
  { symbol: "BNS", name: "Bank of Nova Scotia", region: "Other" },
  { symbol: "ENB", name: "Enbridge", region: "Other" },
  { symbol: "SU", name: "Suncor Energy", region: "Other" },
  { symbol: "CNQ", name: "Canadian Natural Resources", region: "Other" },
  { symbol: "CP", name: "Canadian Pacific Kansas City", region: "Other" },
  { symbol: "BCE", name: "BCE Inc", region: "Other" },
  { symbol: "2222.SR", name: "Saudi Aramco", region: "Other" },
  { symbol: "EZTC3.SA", name: "EZTec", region: "Other" },
  { symbol: "ABEV", name: "Ambev", region: "Other" },
  { symbol: "SE", name: "Sea Limited", region: "Other" },
  { symbol: "GRAB", name: "Grab Holdings", region: "Other" },
  { symbol: "CPNG", name: "Coupang", region: "Other" },
  { symbol: "GLBE", name: "Global-e Online", region: "Other" },
];

export function getStocksByRegion(region?: StockEntry["region"]): StockEntry[] {
  if (!region) return STOCK_UNIVERSE;
  return STOCK_UNIVERSE.filter((s) => s.region === region);
}
