/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OvernightBacktestRouteImport } from './routes/overnight-backtest'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStrategiesRouteImport } from './routes/_authenticated/strategies'
import { Route as AuthenticatedSchedulesRouteImport } from './routes/_authenticated/schedules'
import { Route as AuthenticatedPaperRouteImport } from './routes/_authenticated/paper'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as ApiPublicMarketSearchRouteImport } from './routes/api/public/market/search'
import { Route as ApiPublicMarketQuoteRouteImport } from './routes/api/public/market/quote'
import { Route as ApiPublicMarketOvernightBacktestSingleRouteImport } from './routes/api/public/market/overnight-backtest-single'
import { Route as ApiPublicMarketOvernightBacktestRouteImport } from './routes/api/public/market/overnight-backtest'
import { Route as ApiPublicMarketKlinesRouteImport } from './routes/api/public/market/klines'
import { Route as ApiPublicCronRunBotsRouteImport } from './routes/api/public/cron/run-bots'
import { Route as ApiPublicCronRunBacktestsRouteImport } from './routes/api/public/cron/run-backtests'
import { Route as ApiPublicCronEvaluateAlertsRouteImport } from './routes/api/public/cron/evaluate-alerts'

const OvernightBacktestRoute = OvernightBacktestRouteImport.update({
  id: '/overnight-backtest',
  path: '/overnight-backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStrategiesRoute = AuthenticatedStrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchedulesRoute = AuthenticatedSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaperRoute = AuthenticatedPaperRouteImport.update({
  id: '/paper',
  path: '/paper',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicMarketSearchRoute = ApiPublicMarketSearchRouteImport.update({
  id: '/api/public/market/search',
  path: '/api/public/market/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMarketQuoteRoute = ApiPublicMarketQuoteRouteImport.update({
  id: '/api/public/market/quote',
  path: '/api/public/market/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMarketOvernightBacktestSingleRoute =
  ApiPublicMarketOvernightBacktestSingleRouteImport.update({
    id: '/api/public/market/overnight-backtest-single',
    path: '/api/public/market/overnight-backtest-single',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMarketOvernightBacktestRoute =
  ApiPublicMarketOvernightBacktestRouteImport.update({
    id: '/api/public/market/overnight-backtest',
    path: '/api/public/market/overnight-backtest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMarketKlinesRoute = ApiPublicMarketKlinesRouteImport.update({
  id: '/api/public/market/klines',
  path: '/api/public/market/klines',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRunBotsRoute = ApiPublicCronRunBotsRouteImport.update({
  id: '/api/public/cron/run-bots',
  path: '/api/public/cron/run-bots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRunBacktestsRoute =
  ApiPublicCronRunBacktestsRouteImport.update({
    id: '/api/public/cron/run-backtests',
    path: '/api/public/cron/run-backtests',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronEvaluateAlertsRoute =
  ApiPublicCronEvaluateAlertsRouteImport.update({
    id: '/api/public/cron/evaluate-alerts',
    path: '/api/public/cron/evaluate-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/overnight-backtest': typeof OvernightBacktestRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/paper': typeof AuthenticatedPaperRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/strategies': typeof AuthenticatedStrategiesRoute
  '/api/public/cron/evaluate-alerts': typeof ApiPublicCronEvaluateAlertsRoute
  '/api/public/cron/run-backtests': typeof ApiPublicCronRunBacktestsRoute
  '/api/public/cron/run-bots': typeof ApiPublicCronRunBotsRoute
  '/api/public/market/klines': typeof ApiPublicMarketKlinesRoute
  '/api/public/market/overnight-backtest': typeof ApiPublicMarketOvernightBacktestRoute
  '/api/public/market/overnight-backtest-single': typeof ApiPublicMarketOvernightBacktestSingleRoute
  '/api/public/market/quote': typeof ApiPublicMarketQuoteRoute
  '/api/public/market/search': typeof ApiPublicMarketSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/overnight-backtest': typeof OvernightBacktestRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/paper': typeof AuthenticatedPaperRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/strategies': typeof AuthenticatedStrategiesRoute
  '/api/public/cron/evaluate-alerts': typeof ApiPublicCronEvaluateAlertsRoute
  '/api/public/cron/run-backtests': typeof ApiPublicCronRunBacktestsRoute
  '/api/public/cron/run-bots': typeof ApiPublicCronRunBotsRoute
  '/api/public/market/klines': typeof ApiPublicMarketKlinesRoute
  '/api/public/market/overnight-backtest': typeof ApiPublicMarketOvernightBacktestRoute
  '/api/public/market/overnight-backtest-single': typeof ApiPublicMarketOvernightBacktestSingleRoute
  '/api/public/market/quote': typeof ApiPublicMarketQuoteRoute
  '/api/public/market/search': typeof ApiPublicMarketSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/overnight-backtest': typeof OvernightBacktestRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/paper': typeof AuthenticatedPaperRoute
  '/_authenticated/schedules': typeof AuthenticatedSchedulesRoute
  '/_authenticated/strategies': typeof AuthenticatedStrategiesRoute
  '/api/public/cron/evaluate-alerts': typeof ApiPublicCronEvaluateAlertsRoute
  '/api/public/cron/run-backtests': typeof ApiPublicCronRunBacktestsRoute
  '/api/public/cron/run-bots': typeof ApiPublicCronRunBotsRoute
  '/api/public/market/klines': typeof ApiPublicMarketKlinesRoute
  '/api/public/market/overnight-backtest': typeof ApiPublicMarketOvernightBacktestRoute
  '/api/public/market/overnight-backtest-single': typeof ApiPublicMarketOvernightBacktestSingleRoute
  '/api/public/market/quote': typeof ApiPublicMarketQuoteRoute
  '/api/public/market/search': typeof ApiPublicMarketSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/overnight-backtest'
    | '/alerts'
    | '/paper'
    | '/schedules'
    | '/strategies'
    | '/api/public/cron/evaluate-alerts'
    | '/api/public/cron/run-backtests'
    | '/api/public/cron/run-bots'
    | '/api/public/market/klines'
    | '/api/public/market/overnight-backtest'
    | '/api/public/market/overnight-backtest-single'
    | '/api/public/market/quote'
    | '/api/public/market/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/overnight-backtest'
    | '/alerts'
    | '/paper'
    | '/schedules'
    | '/strategies'
    | '/api/public/cron/evaluate-alerts'
    | '/api/public/cron/run-backtests'
    | '/api/public/cron/run-bots'
    | '/api/public/market/klines'
    | '/api/public/market/overnight-backtest'
    | '/api/public/market/overnight-backtest-single'
    | '/api/public/market/quote'
    | '/api/public/market/search'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/overnight-backtest'
    | '/_authenticated/alerts'
    | '/_authenticated/paper'
    | '/_authenticated/schedules'
    | '/_authenticated/strategies'
    | '/api/public/cron/evaluate-alerts'
    | '/api/public/cron/run-backtests'
    | '/api/public/cron/run-bots'
    | '/api/public/market/klines'
    | '/api/public/market/overnight-backtest'
    | '/api/public/market/overnight-backtest-single'
    | '/api/public/market/quote'
    | '/api/public/market/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OvernightBacktestRoute: typeof OvernightBacktestRoute
  ApiPublicCronEvaluateAlertsRoute: typeof ApiPublicCronEvaluateAlertsRoute
  ApiPublicCronRunBacktestsRoute: typeof ApiPublicCronRunBacktestsRoute
  ApiPublicCronRunBotsRoute: typeof ApiPublicCronRunBotsRoute
  ApiPublicMarketKlinesRoute: typeof ApiPublicMarketKlinesRoute
  ApiPublicMarketOvernightBacktestRoute: typeof ApiPublicMarketOvernightBacktestRoute
  ApiPublicMarketOvernightBacktestSingleRoute: typeof ApiPublicMarketOvernightBacktestSingleRoute
  ApiPublicMarketQuoteRoute: typeof ApiPublicMarketQuoteRoute
  ApiPublicMarketSearchRoute: typeof ApiPublicMarketSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/overnight-backtest': {
      id: '/overnight-backtest'
      path: '/overnight-backtest'
      fullPath: '/overnight-backtest'
      preLoaderRoute: typeof OvernightBacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/strategies': {
      id: '/_authenticated/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof AuthenticatedStrategiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedules': {
      id: '/_authenticated/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AuthenticatedSchedulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/paper': {
      id: '/_authenticated/paper'
      path: '/paper'
      fullPath: '/paper'
      preLoaderRoute: typeof AuthenticatedPaperRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/market/search': {
      id: '/api/public/market/search'
      path: '/api/public/market/search'
      fullPath: '/api/public/market/search'
      preLoaderRoute: typeof ApiPublicMarketSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/market/quote': {
      id: '/api/public/market/quote'
      path: '/api/public/market/quote'
      fullPath: '/api/public/market/quote'
      preLoaderRoute: typeof ApiPublicMarketQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/market/overnight-backtest-single': {
      id: '/api/public/market/overnight-backtest-single'
      path: '/api/public/market/overnight-backtest-single'
      fullPath: '/api/public/market/overnight-backtest-single'
      preLoaderRoute: typeof ApiPublicMarketOvernightBacktestSingleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/market/overnight-backtest': {
      id: '/api/public/market/overnight-backtest'
      path: '/api/public/market/overnight-backtest'
      fullPath: '/api/public/market/overnight-backtest'
      preLoaderRoute: typeof ApiPublicMarketOvernightBacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/market/klines': {
      id: '/api/public/market/klines'
      path: '/api/public/market/klines'
      fullPath: '/api/public/market/klines'
      preLoaderRoute: typeof ApiPublicMarketKlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/run-bots': {
      id: '/api/public/cron/run-bots'
      path: '/api/public/cron/run-bots'
      fullPath: '/api/public/cron/run-bots'
      preLoaderRoute: typeof ApiPublicCronRunBotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/run-backtests': {
      id: '/api/public/cron/run-backtests'
      path: '/api/public/cron/run-backtests'
      fullPath: '/api/public/cron/run-backtests'
      preLoaderRoute: typeof ApiPublicCronRunBacktestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/evaluate-alerts': {
      id: '/api/public/cron/evaluate-alerts'
      path: '/api/public/cron/evaluate-alerts'
      fullPath: '/api/public/cron/evaluate-alerts'
      preLoaderRoute: typeof ApiPublicCronEvaluateAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedPaperRoute: typeof AuthenticatedPaperRoute
  AuthenticatedSchedulesRoute: typeof AuthenticatedSchedulesRoute
  AuthenticatedStrategiesRoute: typeof AuthenticatedStrategiesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedPaperRoute: AuthenticatedPaperRoute,
  AuthenticatedSchedulesRoute: AuthenticatedSchedulesRoute,
  AuthenticatedStrategiesRoute: AuthenticatedStrategiesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OvernightBacktestRoute: OvernightBacktestRoute,
  ApiPublicCronEvaluateAlertsRoute: ApiPublicCronEvaluateAlertsRoute,
  ApiPublicCronRunBacktestsRoute: ApiPublicCronRunBacktestsRoute,
  ApiPublicCronRunBotsRoute: ApiPublicCronRunBotsRoute,
  ApiPublicMarketKlinesRoute: ApiPublicMarketKlinesRoute,
  ApiPublicMarketOvernightBacktestRoute: ApiPublicMarketOvernightBacktestRoute,
  ApiPublicMarketOvernightBacktestSingleRoute:
    ApiPublicMarketOvernightBacktestSingleRoute,
  ApiPublicMarketQuoteRoute: ApiPublicMarketQuoteRoute,
  ApiPublicMarketSearchRoute: ApiPublicMarketSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
